export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SUBTRACT_INGREDIENT = 'SUBTRACT_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'INNIT_INGREDIENTS';
